### ISSUE TITLE
Перевод анонса Rust 1.36

### ISSUE THREAD

**Issue by funkill** [ruRust/translations#1]

**Comment by XX** [comment]
Есть добровольцы на перевод? )
Я смогу заняться переводом только в субботу, что довольно поздно. А вот с вычиткой помогу в любое время.

**Comment by funkill** [comment]
[Draft](https://github.com/rust-lang/blog.rust-lang.org/pull/394)

**Comment by andreevlex** [comment]
А если подключить репу к git-localize?
в стандартном варианте перевода (через PR) кто первый возьмется, то и должен закончить.
с git-localize возможно делать это коллективно и в несколько итераций.

**Comment by funkill** [comment]
Думаю пока не стоит, ибо не разобрались ещё с доступом от аккаунта ruRust.

Пока что можно закоммитить оригинал, как появится, и поверх него уже перевод - чтобы в PR было видно и то, и другое.

**Comment by funkill** [comment]
Можно переводить: https://github.com/ruRust/translations/blob/master/announcements/2019-07-04-Rust-1.36.0.md

**Comment by funkill** [comment]
Перевод выложили до нас: https://habr.com/ru/post/458848/
